config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"
require_relative "whitelist"

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "events#index"
  devise_for :users, path: "/", controllers: { confirmations: "confirmations", omniauth_callbacks: "users/omniauth_callbacks", sessions: "sessions" }

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  resources :programs do
    get :es_reindex, on: :member
    resource :telegram_bot
  end

  get "helps/how-to-connect-telegram-bot", to: "helps#telegram_bot"
  get "helps/how-to-connect-telegram-account", to: "helps#telegram_account"

  scope module: :programs do
    resource :setting, only: [:show, :update]
  end

  resources :users do
    put :disconnect_telegram, on: :member
  end

  resource :locale, only: [:update]

  resources :events do
    scope module: :events do
      resources :event_milestones
      resource :preview, only: [:show]
      resources :follow_ups, only: [:new, :create, :update]
    end

    get :download, on: :collection
    get :search, on: :collection
    put :unlock, on: :member
  end

  resources :schedules do
    get :activate, on: :member
    get :deactivate, on: :member
  end

  resources :medisys_feeds, only: :index
  resources :medisies do
    get :help, on: :collection
  end

  resources :event_types do
    get :shared, on: :member
    get :unshared, on: :member
  end

  resources :milestones do
    scope module: :milestones do
      resource :message
    end

    put :reorder, on: :collection
  end

  resources :client_apps do
    get :activate, on: :member
    get :deactivate, on: :member
    get :info, on: :collection
  end

  resources :webhooks, except: [:show] do
    get :activate, on: :member
    get :deactivate, on: :member
  end

  resource :download, only: [:show]
  resources :about_us, only: [:index]
  resources :locations, only: [:index]

  resources :maps

  resources :templates

  # API
  namespace :api do
    namespace :v1 do
      resources :milestones do
        resources :fields, only: [:index], module: "milestone"
      end
      resources :event_types, only: [:index]
      resources :events, except: [:new, :edit, :destroy]
      resources :event_milestones, only: [:create, :update]
    end
  end

  # Pumi
  mount Pumi::Engine => "/pumi"

  constraints Whitelist do
    # Telegram
    telegram_webhook TelegramWebhooksController
  end

  if Rails.env.production?
    # Sidekiq
    authenticate :user, lambda { |u| u.system_admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end

    # Dashboard
    authenticate :user, lambda { |u| u.system_admin? || u.program_admin? } do
      resource :dashboard, only: :show
    end
  else
    mount Sidekiq::Web => "/sidekiq"
    resource :dashboard, only: :show
  end
end

app/models/message.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: messages
#
#  id           :bigint           not null, primary key
#  message      :text
#  milestone_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#


class Message < ApplicationRecord
  CHANNELS = %w(email telegram)

  belongs_to :milestone
  has_one :telegram_notification, class_name: "Notifications::TelegramNotification", dependent: :destroy
  has_one :email_notification, dependent: :destroy

  # Nested attribute
  accepts_nested_attributes_for :email_notification, allow_destroy: true
  accepts_nested_attributes_for :telegram_notification, allow_destroy: true

  validates :message, presence: true

  def self.channels
    %i(telegram_notification email_notification)
  end
end

app/models/milestone.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: milestones
#
#  id            :bigint           not null, primary key
#  display_order :integer
#  final         :boolean          default(FALSE)
#  is_default    :boolean          default(FALSE)
#  name          :string
#  status        :integer
#  verified      :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  creator_id    :integer
#  program_id    :integer
#

class Milestone < ApplicationRecord
  # Association
  belongs_to :program
  belongs_to :creator, class_name: "User"
  has_one    :message
  has_one    :telegram_notification, class_name: "Notifications::TelegramNotification"
  has_one    :email_notification, through: :message
  has_many   :sections, dependent: :destroy
  has_many   :fields, dependent: :destroy

  enum status: {
    root: 1,
    verified: 2,
    final: 3,
  }

  STATUSES = statuses.keys.map { |r| [r.titlecase, r] }
  PREVIOUS_MILESTONE = "previous_milestone"

  # Validation
  validates :name, presence: true, uniqueness: { scope: [:program_id] }
  validates :status, uniqueness: { scope: :program_id }, allow_nil: true
  validate :validate_unique_section_name

  before_validation :set_default_section, unless: :root?
  before_create :set_display_order

  # Scope
  default_scope { order(display_order: :asc) }
  scope :root, -> { where(status: :root).first }
  scope :finals, -> { where(status: :final) }
  scope :verified, -> { where(status: :verified).first }

  # Deligation
  delegate :message, to: :telegram, prefix: :telegram, allow_nil: true
  delegate :format_name, to: :program, prefix: :program, allow_nil: true

  # Nested attribute
  accepts_nested_attributes_for :sections, allow_destroy: true

  # Class methods
  def self.create_root(creator_id)
    create(name: "New", status: :root, sections_attributes: Section.roots, creator_id: creator_id)
  end

  # Instand methods
  def template_fields
    return Event.template_fields(program) if self.root?

    fields.map do |field|
      {
        code: "#{EventMilestone.dynamic_template_code}#{field.id}_#{field.format_name}",
        label: field.name
      }
    end
  end

  def extra_fields
    root? ? [{ code: :event_type_id, type: :integer, label: "Event Type ID" }] : [{ code: :event_uuid, type: :string, label: "Event Uuid" }]
  end

  def format_name
    name.downcase.split(" ").join("_")
  end

  def build_default_section
    self.sections_attributes = Section.defaults
  end

  def status_collection
    return [["Root", "root"]] if root?

    Milestone::STATUSES.drop(1)
  end

  def telegram_invalid_configure?
    program.telegram_bot.nil? || !program.telegram_bot.actived?
  end

  def telegram_not_ready?
    !program.telegram_bot.enabled? || telegram_notification.nil? || telegram_notification.chat_groups.blank?
  end

  def email_not_ready?
    !program.enable_email_notification? || email_notification.nil? || email_notification.emails.blank?
  end

  def relevant_fields(scope = :dates)
    fields = Field.unscoped.joins(:milestone).send(scope)
              .where("milestones.display_order": (1..display_order.to_i).to_a)
              .where("milestones.program_id": program_id)
              .order("milestones.display_order ASC")
    arr = fields.includes(:milestone).map { |field| field.relevant_format }
    arr.push(previous_milestone_field) if scope == :dates && !self.root?
    arr
  end

  private
    def validate_unique_section_name
      validate_uniqueness_of_in_memory(sections, %i[name], "duplicate")
    end

    def set_display_order
      self.display_order ||= program.milestones.maximum(:display_order).to_i + 1
    end

    def set_default_section
      self.sections_attributes = Section.defaults if sections.select { |section| section.default }.length == 0
    end

    def previous_milestone_field
      {
        name: "Previous milestone::Conducted on",
        code: "#{PREVIOUS_MILESTONE}::conducted_at"
      }
    end
end

app/models/program.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: programs
#
#  id                        :bigint           not null, primary key
#  enable_email_notification :boolean          default(FALSE)
#  language_code             :string
#  logo                      :string
#  name                      :string
#  national_zoom_level       :integer          default(7)
#  provincial_zoom_level     :integer          default(10)
#  risk_assessment_guideline :string
#  unlock_event_duration     :integer          default(7)
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  creator_id                :integer
#

class Program < ApplicationRecord
  include Programs::ElasticsearchConcern

  mount_uploader :logo, LogoUploader
  mount_uploader :risk_assessment_guideline, LogoUploader

  belongs_to :creator, class_name: "User"
  LANGUAGES = [
    %w[English en],
    %w[ខ្មែរ km]
  ].freeze

  has_many  :users
  has_many  :client_apps
  has_many  :events
  has_many  :event_types
  has_many  :milestones
  has_many  :fields, through: :milestones
  has_many  :webhooks
  has_many  :chat_groups
  has_one   :telegram_bot, dependent: :destroy
  has_many  :templates
  has_many  :medisies

  has_many  :program_telegram_notifications
  has_many  :telegram_notification_receivers, through: :program_telegram_notifications, source: :user

  validates :name, presence: true
  validates :unlock_event_duration, numericality: { greater_than_or_equal_to: 1,  only_integer: true }
  validates :national_zoom_level, inclusion: 0..20
  validates :provincial_zoom_level, inclusion: 0..20

  before_create :set_default_language
  after_create :create_root_milestone
  after_create :create_unknown_event_type
  after_create { ProgramWorker.perform_async(id) }

  accepts_nested_attributes_for :telegram_bot, allow_destroy: true

  delegate :enabled, to: :telegram_bot, prefix: :telegram_bot, allow_nil: true

  def format_name
    name.downcase.split(" ").join("_")
  end

  def enable_telegram?
    self.telegram_bot_enabled
  end

  def logo_or_default
    logo_url || "default_logo.png"
  end

  def siblings
    self.class.where.not(id: id)
  end

  def has_final_milestone?
    milestones.finals.present?
  end

  private
    def set_default_language
      self.language_code ||= "en"
    end

    def create_root_milestone
      milestones.create_root(creator_id)
    end

    def create_unknown_event_type
      event_types.create_root(creator_id)
    end
end

app/controllers/api/v1/milestone/fields_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Milestone
      class FieldsController < ::Api::V1::ApplicationController
        def index
          milestone = ::Milestone.find(params[:milestone_id])

          render json: milestone.fields, meta: { milestone: milestone, extra_fields: milestone.extra_fields }, adapter: :json, root: "fields"
        end
      end
    end
  end
end

app/controllers/api/v1/milestones_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class MilestonesController < ApplicationController
      def index
        milestones = current_program.milestones

        render json: milestones
      end
    end
  end
end

app/controllers/milestones/messages_controller.rb
# frozen_string_literal: true

module Milestones
  class MessagesController < ::ApplicationController
    before_action :set_milestone
    before_action :set_chat_group

    def show
      @message = @milestone.message
    end

    def new
      @message = @milestone.build_message
      @message.build_telegram_notification
      @message.build_telegram_notification.notification_chat_groups.build
      @message.build_email_notification
    end

    def create
      @message = @milestone.build_message(message_params)

      if @message.save
        redirect_to milestone_message_url(@milestone)
      else
        flash.now[:alert] = @message.errors.full_messages
        render :new
      end
    end

    def edit
      @message = @milestone.message
      @message.build_telegram_notification if @message.telegram_notification.nil?
      @message.build_telegram_notification.notification_chat_groups.build if @message.telegram_notification.notification_chat_groups.empty?
      @message.build_email_notification if @message.email_notification.nil?
    end

    def update
      @message = @milestone.message

      if @message.update_attributes(message_params)
        redirect_to milestone_message_url(@milestone)
      else
        flash.now[:alert] = @message.errors.full_messages
        render :edit
      end
    end

    private
      def message_params
        params.require(:message).permit(:message,
          telegram_notification_attributes:
          [
            :milestone_id,
            notification_chat_groups_attributes: [:id, :chat_group_id]
          ],
          email_notification_attributes: [:id, :emails]
        )
      end

      def set_milestone
        @milestone = Milestone.find(params[:milestone_id])
      end

      def set_chat_group
        @chat_groups = current_program.chat_groups.telegrams
      end
  end
end

app/controllers/milestones_controller.rb
# frozen_string_literal: true

class MilestonesController < ::ApplicationController
  def index
    @pagy, @milestones = pagy(authorize current_program.milestones.includes(:fields, :message))
  end

  def new
    @milestone = authorize current_program.milestones.new
    @milestone.build_default_section
  end

  def create
    @milestone = authorize current_program.milestones.new(milestone_params)

    if @milestone.save
      redirect_to milestones_url
    else
      render :new
    end
  end

  def edit
    @milestone = authorize Milestone.find(params[:id])
  end

  def update
    @milestone = authorize Milestone.find(params[:id])

    if @milestone.update_attributes(milestone_params)
      redirect_to milestones_url
    else
      render :edit
    end
  end

  def destroy
    @milestone = authorize Milestone.find(params[:id])
    @milestone.destroy

    redirect_to milestones_url
  end

  def reorder
    authorize Milestone, :update?

    current_program.milestones.update_order!(params[:ids])
  end

  private
    def milestone_params
      params.require(:milestone).permit(
        :name, :display_order, :status,
        sections_attributes: [
          :id, :name, :default, :_destroy, :display,
          fields_attributes: [
            :id, :name, :field_type, :required, :display_order, :code, :entry_able,
            :mapping_field_id, :_destroy, :tracking, :description, :relevant, :is_milestone_datetime,
            :template_file, :template_name, :remove_template_file, validations: {},
            field_options_attributes: %i[id name value color display_order _destroy]
          ]
        ]
      ).merge(creator_id: current_user.id)
    end
end

app/helpers/milestones_helper.rb
# frozen_string_literal: true

module MilestonesHelper
  def telegram_icon_status(milestone)
    return "" unless milestone.message.present?

    if milestone.telegram_invalid_configure?
      return '<a class="btn btn-small text-secondary position-relative" title="Telegram bot is invalid configure" data-toggle="tooltip"><i class="fab fa-telegram font-size-24"></i><i class="far fa-times-circle icon-red invalid-config-icon"></i></a>'
    end

    if milestone.telegram_not_ready?
      return '<a class="btn btn-small text-secondary" title="Telegram bot is disabled or no group notification selected" data-toggle="tooltip"><i class="fab fa-telegram font-size-24"></i></a>'
    end

    "<a class='btn btn-small text-success' data-trigger='hover' data-content='#{milestone.telegram_notification.chat_groups.pluck(:title).join('; ')}' data-toggle='popover' title='Notify to'><i class='fab fa-telegram font-size-24 active-telegram-icon'></i></a>"
  end

  def email_icon_status(milestone)
    return "" unless milestone.message.present?

    if milestone.email_not_ready?
      return '<a class="btn btn-small text-secondary" title="Email is disabled or no email notification selected" data-toggle="tooltip"><i class="far fa-envelope font-size-24"></i></a>'
    end

    "<a class='btn btn-small text-danger' data-trigger='hover' data-content='#{milestone.email_notification.emails.join('; ')}' data-toggle='popover' title='Notify to'><i class='far fa-envelope font-size-24'></i></a>"
  end
end

app/views/milestones/messages/_form.html.haml
- content_for :header_title do
  = "#{@milestone.name}: #{t('milestone.notification')}"

= simple_form_for @message, url: milestone_message_path(@milestone), html: { id: 'message-form' } do |f|
  .content-wrapper
    .flex-row
      .col-left
        = f.input :message, label: t('milestone.message'), input_html: { rows: 3 }
        = render 'stepper_template_fields'

      .col-right
        = f.simple_fields_for :email_notification do |ef|

          .form-group
            %label
              = t('milestone.email_to')

            - if !current_program.enable_email_notification?
              .small.ml-4= t('milestone.to_enable_email', url: setting_path).html_safe
            - else
              = ef.input :emails, label: false, input_html: { id: 'notification-emails' }

        = f.simple_fields_for :telegram_notification do |tf|
          = tf.hidden_field :milestone_id, value: @milestone.id

          .form-group
            %label
              = t('milestone.telegram_chat_group')
              - if current_program.enable_telegram? && @chat_groups.present?
                = link_to t('shared.need_help'), helps_how_to_connect_telegram_bot_path(anchor: 'group'), class: 'small text-primary', 'data-turbolinks': false

            - if !current_program.enable_telegram?
              .small.ml-4= t('milestone.to_enable_telegram', url: setting_path).html_safe

            - else
              - @chat_groups.each_with_index do |chat_group, index|
                .form-check
                  = check_box_tag "message[telegram_notification_attributes][notification_chat_groups_attributes][#{index}][chat_group_id]", chat_group.id, @message.telegram_notification.chat_group_ids.include?(chat_group.id), class: 'form-check-input', id: dom_id(chat_group)
                  %label.form-check-label{for: dom_id(chat_group)}
                    - if chat_group.is_active?
                      %span= chat_group.title
                    - else
                      %strike{'data-toggle'=>"tooltip", 'data-placement' => "top", title: chat_group.reason}= chat_group.title

              - unless @chat_groups.present?
                %div
                  %span.small.ml-4= t('milestone.learn_more_to_add_bot_to_group', url: helps_how_to_connect_telegram_bot_path(anchor: 'group')).html_safe

    .actions
      = f.submit t('shared.save'), class: 'btn btn-primary'
      = link_to t('shared.cancel'), milestone_message_path, class: 'btn btn-secondary'

app/views/milestones/messages/_message.html.haml
.w-75.view-center
  %ul.list.flex1.pt-0.px-1
    %li
      %span.type= "#{t('milestone.message')}:"
      %span.value= @message.message

    %li
      %span.type= "#{t('milestone.email')}:"
      %span.value
        - if emails = @message.email_notification.present? && @message.email_notification.emails.presence
          - emails.each do |email|
            %span= email

        - else
          = '_'

    %li
      %span.type= "#{t('milestone.telegram_chat_group')}:"
      %span.value
        - if chat_groups = @message.telegram_notification.present? && @message.telegram_notification.chat_groups.presence
          - chat_groups.each do |group|
            - if group.is_active?
              %span= group.title
            - else
              %strike{'data-toggle'=>"tooltip", 'data-placement' => "top", title: group.reason}= group.title

        - else
          = '_'

  .actions
    = link_to t('shared.edit'), edit_milestone_message_path(@milestone), class: 'btn btn-primary'

app/views/milestones/messages/_stepper_template_fields.html.haml
.content-element.circles-list.flex1
  %ol
    - milestones = current_program.milestones
    - milestones.each do |milestone|
      %li{ class: ('inactive' unless milestone.root? || milestone == @milestone) }
        %span.number
          .milestone-name= milestone.name
        .template-fields-wrapper
          .template-fields
            - if milestone.root? || milestone == @milestone
              - milestone.template_fields.each do |field|
                = link_to "{{#{field[:label]}}}", '#', class: 'template-field text-primary mr-2', data: {code: field[:code]}

app/views/milestones/messages/show.html.haml
- content_for :header_title do
  = "#{@milestone.name}: #{t('milestone.notification')}"

.d-flex.justify-content-end.mb-3
  = link_to t('shared.done'), milestones_path, class: 'btn btn-primary btn-sm'

.card.shadow.mb-4
  .card-body
    - if !current_program.enable_email_notification? && !current_program.enable_telegram?
      .w-50.view-center.flex1.flex-row-vertical-center
        .flex1.text-center= t('milestone.go_to_setting', url: setting_path).html_safe

    - else
      - if @message.present?
        = render 'message'

      - else
        .w-50.view-center.flex1.flex-row-vertical-center
          .flex1.text-center
            %div= t('milestone.setup_message_instruction')
            .actions
              = link_to t('milestone.setup'), new_milestone_message_path(@milestone), class: 'btn btn-primary'