config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"
require_relative "whitelist"

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "events#index"
  devise_for :users, path: "/", controllers: { confirmations: "confirmations", omniauth_callbacks: "users/omniauth_callbacks", sessions: "sessions" }

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  resources :programs do
    get :es_reindex, on: :member
    resource :telegram_bot
  end

  get "helps/how-to-connect-telegram-bot", to: "helps#telegram_bot"
  get "helps/how-to-connect-telegram-account", to: "helps#telegram_account"

  scope module: :programs do
    resource :setting, only: [:show, :update]
  end

  resources :users do
    put :disconnect_telegram, on: :member
  end

  resource :locale, only: [:update]

  resources :events do
    scope module: :events do
      resources :event_milestones
      resource :preview, only: [:show]
      resources :follow_ups, only: [:new, :create, :update]
    end

    get :download, on: :collection
    get :search, on: :collection
    put :unlock, on: :member
  end

  resources :schedules do
    get :activate, on: :member
    get :deactivate, on: :member
  end

  resources :medisys_feeds, only: :index
  resources :medisies do
    get :help, on: :collection
  end

  resources :event_types do
    get :shared, on: :member
    get :unshared, on: :member
  end

  resources :milestones do
    scope module: :milestones do
      resource :message
    end

    put :reorder, on: :collection
  end

  resources :client_apps do
    get :activate, on: :member
    get :deactivate, on: :member
    get :info, on: :collection
  end

  resources :webhooks, except: [:show] do
    get :activate, on: :member
    get :deactivate, on: :member
  end

  resource :download, only: [:show]
  resources :about_us, only: [:index]
  resources :locations, only: [:index]

  resources :maps

  resources :templates

  # API
  namespace :api do
    namespace :v1 do
      resources :milestones do
        resources :fields, only: [:index], module: "milestone"
      end
      resources :event_types, only: [:index]
      resources :events, except: [:new, :edit, :destroy]
      resources :event_milestones, only: [:create, :update]
    end
  end

  # Pumi
  mount Pumi::Engine => "/pumi"

  constraints Whitelist do
    # Telegram
    telegram_webhook TelegramWebhooksController
  end

  if Rails.env.production?
    # Sidekiq
    authenticate :user, lambda { |u| u.system_admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end

    # Dashboard
    authenticate :user, lambda { |u| u.system_admin? || u.program_admin? } do
      resource :dashboard, only: :show
    end
  else
    mount Sidekiq::Web => "/sidekiq"
    resource :dashboard, only: :show
  end
end

app/views/shared/topbars/_switch_locale.haml
- current_locale = available_locales.find { |locale| locale[:code] == I18n.locale.to_s }

%li.nav-item.dropdown.no-arrow.mx-1
  / Language display
  %a#languageDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}

    = image_tag current_locale[:image], alt: "locale", size: "24x24", class: "mr-2", 'data-language-code' => I18n.locale
    %span.text-gray-600.small= current_locale[:label]
    %i.fas.fa-angle-down.fa-fw

  / Language dropdown list
  .dropdown-list.dropdown-menu.dropdown-menu-right.shadow.animated--grow-in.p-0{"aria-labelledby" => "languageDropdown"}
    = simple_form_for(current_user, url: locale_path, method: :put, remote: true, html: { id: "switch-locale" }) do |f|
      = f.hidden_field :locale

      - available_locales.each_with_index do |locale, index|
        %a.switch-locale.dropdown-item.d-flex.align-items-center.small{'data-locale' => locale[:code], href: '#', class: ('border-bottom' if index < available_locales.length)}
          .dropdown-list-image.mr-3
            = image_tag locale[:image], alt: "locale", size: "24x24"
          .text-truncate= locale[:label]

app/views/shared/topbars/_user_profile.haml
%li.nav-item.dropdown.no-arrow
  / User display
  %a#userDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    .d-flex
      .d-flex.flex-column.align-items-center.mr-2
        %span.d-none.d-lg-inline.text-gray-600.small= current_user.display_name
        %small.text-gray-600.program-name= "@#{current_program.try(:name) || 'SYSTEM'}"

      = image_tag 'default_profile.png', alt: 'profile', class: 'img-profile rounded-circle'

      %span.small.position-absolute{style: 'top: 0; right: 0;'}
        = telegram_account_status(current_user).html_safe

  / Profile dropdown
  .dropdown-list.dropdown-menu.dropdown-menu-right.shadow.animated--grow-in.p-0{"aria-labelledby" => "userDropdown"}

    / Profile email
    .dropdown-item.profile-wrapper.small.border-bottom
      .dropdown-list-image.mr-2
        = image_tag 'default_profile.png', alt: 'profile', class: 'img-profile rounded-circle'
      %strong.ellipsis.flex-grow-1{title: current_user.email}
        = current_user.email

      = telegram_account_status(current_user).html_safe

    / Event Setting
    = link_to user_path(current_user), class: 'dropdown-item d-flex align-items-center small border-bottom', remote: true do
      .dropdown-list-image.mr-2
        %i.fas.fa-bell.fa-sm.text-gray-600
      = t('user.event_notification_setting')

    / Telegram account help
    = link_to helps_how_to_connect_telegram_account_path, class: 'dropdown-item d-flex align-items-center small border-bottom' do
      .dropdown-list-image.mr-2.text-gray-600
        = icon_telegram.html_safe
      = t('user.telegram_account_help')

    / Logout
    = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item d-flex align-items-center small' do
      .dropdown-list-image.mr-2
        %i.fas.fa-sign-out-alt.fa-sm.text-gray-600
      = t("sidebar.logout")