config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"
require_relative "whitelist"

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "events#index"
  devise_for :users, path: "/", controllers: { confirmations: "confirmations", omniauth_callbacks: "users/omniauth_callbacks", sessions: "sessions" }

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", :via => :put, :as => :update_user_confirmation
  end

  resources :programs do
    get :es_reindex, on: :member
    resource :telegram_bot
  end

  get "helps/how-to-connect-telegram-bot", to: "helps#telegram_bot"
  get "helps/how-to-connect-telegram-account", to: "helps#telegram_account"

  scope module: :programs do
    resource :setting, only: [:show, :update]
  end

  resources :users do
    put :disconnect_telegram, on: :member
  end

  resource :locale, only: [:update]

  resources :events do
    scope module: :events do
      resources :event_milestones
      resource :preview, only: [:show]
      resources :follow_ups, only: [:new, :create, :update]
    end

    get :download, on: :collection
    get :search, on: :collection
    put :unlock, on: :member
  end

  resources :schedules do
    get :activate, on: :member
    get :deactivate, on: :member
  end

  resources :medisys_feeds, only: :index
  resources :medisies do
    get :help, on: :collection
  end

  resources :event_types do
    get :shared, on: :member
    get :unshared, on: :member
  end

  resources :milestones do
    scope module: :milestones do
      resource :message
    end

    put :reorder, on: :collection
  end

  resources :client_apps do
    get :activate, on: :member
    get :deactivate, on: :member
    get :info, on: :collection
  end

  resources :webhooks, except: [:show] do
    get :activate, on: :member
    get :deactivate, on: :member
  end

  resource :download, only: [:show]
  resources :about_us, only: [:index]
  resources :locations, only: [:index]

  resources :maps

  resources :templates

  # API
  namespace :api do
    namespace :v1 do
      resources :milestones do
        resources :fields, only: [:index], module: "milestone"
      end
      resources :event_types, only: [:index]
      resources :events, except: [:new, :edit, :destroy]
      resources :event_milestones, only: [:create, :update]
    end
  end

  # Pumi
  mount Pumi::Engine => "/pumi"

  constraints Whitelist do
    # Telegram
    telegram_webhook TelegramWebhooksController
  end

  if Rails.env.production?
    # Sidekiq
    authenticate :user, lambda { |u| u.system_admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end

    # Dashboard
    authenticate :user, lambda { |u| u.system_admin? || u.program_admin? } do
      resource :dashboard, only: :show
    end
  else
    mount Sidekiq::Web => "/sidekiq"
    resource :dashboard, only: :show
  end
end

app/models/schedule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules
#
#  id                       :uuid             not null, primary key
#  channels                 :string           default([]), is an Array
#  date_index               :integer
#  deadline_duration_in_day :integer
#  emails                   :text             default([]), is an Array
#  enabled                  :boolean          default(TRUE)
#  follow_up_hour           :integer
#  interval_type            :integer
#  interval_value           :integer
#  message                  :text
#  name                     :string
#  type                     :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  program_id               :integer
#

class Schedule < ApplicationRecord
  include FollowUps::Channel

  # Association
  belongs_to :program

  # Validation
  validates :name, presence: true
  validates :type, presence: true
  validates :message, presence: true
  validates :interval_type, presence: true
  validates :interval_value, presence: true
  validates :follow_up_hour, presence: true
  validates :follow_up_hour, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 23 }, allow_nil: true
  validates :emails, presence: true, if: :summary_schedule?
  validates :deadline_duration_in_day, presence: true, if: :summary_schedule?
  validates :deadline_duration_in_day, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true

  enum interval_type: {
    day: 1,
    week: 2,
    month: 3
  }

  before_validation :set_type
  before_validation :set_interval_value_and_channel, if: :summary_schedule?

  default_scope { order(updated_at: :desc) }

  # Contant
  TYPES = %w(Schedules::EventSchedule Schedules::SummarySchedule)

  # Instant method
  def reached_time?
    raise "Abstract Method"
  end

  def display_message
    raise "Abstract Method"
  end

  def duration_in_day
    interval_value * duration_in_type
  end

  def summary_schedule?
    type == "Schedules::SummarySchedule"
  end

  def event_schedule?
    type == "Schedules::EventSchedule"
  end

  def duration_in_type
    case interval_type
    when "week"
      7
    when "month"
      30
    else
      1
    end
  end

  def start_date
    interval_value.send("#{interval_type}").ago
  end

  # Class method
  def self.types
    TYPES.map { |t| [t.split("::").last, t] }
  end

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Schedule.model_name
      end
    end
    super
  end

  private
    def set_type
      self.type ||= "Schedules::EventSchedule"
    end

    def set_interval_value_and_channel
      self.interval_value = 1
      self.channels = ["email"]
    end
end

app/models/schedules/event_schedule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules
#
#  id                       :uuid             not null, primary key
#  channels                 :string           default([]), is an Array
#  date_index               :integer
#  deadline_duration_in_day :integer
#  emails                   :text             default([]), is an Array
#  enabled                  :boolean          default(TRUE)
#  follow_up_hour           :integer
#  interval_type            :integer
#  interval_value           :integer
#  message                  :text
#  name                     :string
#  type                     :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  program_id               :integer
#

module Schedules
  class EventSchedule < ::Schedule
    # Intant method
    def send_notification_async
      channels.each do |channel|
        notify_to_events(channel)
      end
    end

    def template_fields
      ::Templates::EventScheduleField.all
    end

    def reached_time?
      follow_up_hour == Time.zone.now.hour
    end

    def short_description
      description("event_schedule_short_info")
    end

    def full_description
      description("event_schedule_full_info")
    end

    def display_message(event)
      ScheduleMessageInterpreter.new(self, event).interpreted_message
    end

    def icon_html
      "<i class='fa-regular fa-calendar-check'></i>"
    end

    def display_type
      I18n.t("schedule.event_schedule")
    end

    private
      def description(label)
        I18n.t("schedule.#{label}",
          interval_value: "<b>#{interval_value}</b>",
          interval_type: "<b>" + I18n.t("schedule.#{interval_type}") + "</b>",
          follow_up_hour: "<b>#{follow_up_hour}:00</b>"
        )
      end

      def notify_to_events(channel)
        events = program.events.uncloseds.reached_intervals(duration_in_day)

        events.each do |event|
          notify("Notifiers::EventSchedule#{channel.titlecase}Notifier".constantize.new(self, event), channel)
        end
      end
  end
end

app/models/schedules/summary_schedule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules
#
#  id                       :uuid             not null, primary key
#  channels                 :string           default([]), is an Array
#  date_index               :integer
#  deadline_duration_in_day :integer
#  emails                   :text             default([]), is an Array
#  enabled                  :boolean          default(TRUE)
#  follow_up_hour           :integer
#  interval_type            :integer
#  interval_value           :integer
#  message                  :text
#  name                     :string
#  type                     :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  program_id               :integer
#

module Schedules
  class SummarySchedule < ::Schedule
    # Intant method
    def send_notification_async
      channels.each do |channel|
        notify("Notifiers::SummarySchedule#{channel.titlecase}Notifier".constantize.new(self), channel)
      end
    end

    def template_fields
      ::Templates::SummaryScheduleField.all
    end

    def reached_time?
      follow_up_hour == Time.zone.now.hour && reached_day?
    end

    def reached_day?
      return true if day?
      return date_index == Time.zone.now.wday if week?

      date_index == Time.zone.now.mday
    end

    def short_description
      discription("summary_schedule_short_info")
    end

    def full_description
      discription("summary_schedule_full_info")
    end

    def display_message
      ScheduleMessageInterpreter.new(self).interpreted_message
    end

    def icon_html
      "<i class='fa-regular fa-clipboard'></i>"
    end

    def display_type
      I18n.t("schedule.summary_schedule")
    end

    private
      def discription(label)
        I18n.t("schedule.#{label}",
          interval_type: "<b>" + I18n.t("schedule.#{interval_type}") + "</b>",
          follow_up_hour: "<b>#{follow_up_hour}:00</b>",
          date_index: "<b>#{display_date_index}</b>"
        )
      end

      def display_date_index
        return "" if day?
        return I18n.t("date.day_names")[date_index] if week?

        date_index
      end
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  def index
    @pagy, @schedules = pagy(policy_scope(authorize Schedule.all))
  end

  def new
    @schedule = authorize Schedule.new(type: params[:type])
  end

  def create
    @schedule = authorize Schedule.new(schedule_params)

    if @schedule.save
      redirect_to schedules_url
    else
      render :new
    end
  end

  def edit
    @schedule = authorize Schedule.find(params[:id])
  end

  def update
    @schedule = authorize Schedule.find(params[:id])

    if @schedule.update_attributes(schedule_params)
      redirect_to schedules_url
    else
      render :edit
    end
  end

  def destroy
    @schedule = authorize Schedule.find(params[:id])
    @schedule.destroy

    redirect_to schedules_url
  end

  def activate
    @schedule = authorize Schedule.find(params[:id]), :update?
    @schedule.update(enabled: true)

    flash[:notice] = "Activate successfully"
    redirect_to schedules_url
  end

  def deactivate
    @schedule = authorize Schedule.find(params[:id]), :update?
    @schedule.update(enabled: false)

    flash[:notice] = "Deactivate successfully"
    redirect_to schedules_url
  end

  private
    def schedule_params
      params.require(:schedule)
            .permit(:name, :type, :interval_type, :interval_value,
              :follow_up_hour, :date_number, :message, :emails,
              :date_index, :deadline_duration_in_day,
              channels: []
            ).merge(program_id: current_program.id)
    end
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

module SchedulesHelper
  def status_html(enabled)
    return "<span class='text-success'>#{t('shared.active')}</span>" if enabled

    "<span class='text-danger'>#{t('shared.inactive')}</span>"
  end

  def schedule_types
    [
      {
        type: "Schedules::EventSchedule",
        label: t("schedule.new_event_schedule"),
        icon: "<i class='fa-regular fa-calendar-check'></i>"
      },
      { type: "Schedules::SummarySchedule",
        label: t("schedule.new_summary_schedule"),
        icon: "<i class='fa-regular fa-clipboard'></i>"
      }
    ]
  end
end

app/views/schedules/_action_buttons.haml
- if policy(schedule).update?
  %button.btn{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    %i.fas.fa-ellipsis-v

  .dropdown-menu.dropdown-menu-right
    - if schedule.enabled?
      = link_to deactivate_schedule_path(schedule), class: "btn dropdown-item", :data => {:confirm => t('schedule.are_you_sure_to_deactivate', name: schedule.name)} do
        %i.fas.fa-ban.drop-menu-icon
        %span= t('shared.deactivate')

    - else
      = link_to activate_schedule_path(schedule), class: "btn dropdown-item" do
        %i.fas.fa-check.drop-menu-icon
        %span= t('shared.activate')

    - if policy(schedule).update?
      = link_to edit_schedule_path(schedule), class: "btn dropdown-item" do
        %i.fas.fa-pen.drop-menu-icon
        %span= t('shared.edit')

    - if policy(schedule).destroy?
      = link_to schedule_path(schedule), method: :delete, class: "btn dropdown-item", :data => {:confirm => t('schedule.are_you_sure_to_delete', name: schedule.name)} do
        %i.fas.fa-trash-alt.drop-menu-icon
        %span= t('shared.delete')

app/views/schedules/_channels.haml
/ Channels
.form-group
  %label
    = t('schedule.notify_to_channel')
    %abbr{title: 'required'} *

  = hidden_field_tag "schedule[channels][]", nil

  .d-flex
    / Channel: Email
    .mr-2
      %label.channel.flex-grow-1{ for: "email" }
        %i.fas.fa-check-circle.tick-icon
        = icon_email.html_safe
        %span= t("event.email")

        %input#email.form-check-input.invisible{ type: "checkbox", value: "email", name: "schedule[channels][]", checked: f.object.channels.include?('email') }


    / Channel: Telegram
    - title = TelegramBot.has_system_bot? ? '' : t("event.no_system_bot_configure")
    .ml-2{ 'data-toggle' => 'tooltip', 'data-title' => title }
      %label.channel{ for: 'ch_telegram', class: ('disabled' unless TelegramBot.has_system_bot? ) }
        %i.fas.fa-check-circle.tick-icon
        = icon_telegram.html_safe
        %span= t("event.telegram")

        %input#ch_telegram.form-check-input.invisible{ type: "checkbox", value: "telegram", name: "schedule[channels][]", checked: f.object.channels.include?('telegram') }

  .d-block.invalid-feedback
    = f.object.errors[:channels].join(', ')

app/views/schedules/_form.html.haml
.w-50.view-center.form-wrapper
  = simple_form_for @schedule do |f|
    = f.input :name, label: t('schedule.name')
    = f.input :type, as: :hidden

    = render "schedule_notify", f: f

    = f.input :message, label: t('schedule.message')

    .form-group
      - @schedule.template_fields.each do |field|
        %span{ 'data-toggle' => 'tooltip', 'data-title' => field[:description], 'data-html' => 'true'}
          = link_to "{{#{field[:code]}}}", '#', class: 'template-field text-primary mr-2', data: {code: field[:code]}

    - if f.object.summary_schedule?
      = f.input :deadline_duration_in_day, label: t('schedule.dealine_duration').html_safe, input_html: { min: 1 }

      .form-group
        %label= t('schedule.to').html_safe
        %input#schedule_emails.form-control{:name => "schedule[emails]", 'data-emails' => current_program.users.pluck(:email).to_json, value: @schedule.emails.join(', ') }

    - if f.object.event_schedule?
      = render "channels", f: f

    .actions
      = f.submit t('shared.save'), class: 'btn btn-primary'
      = link_to t('shared.cancel'), schedules_path, class: 'btn btn-secondary'

app/views/schedules/_schedule.haml
%tr
  %td= @pagy.from + schedule_counter
  %td
    %span.mr-2{ 'data-toggle' => 'tooltip', 'title' => schedule.display_type }
      = schedule.icon_html.html_safe
    = schedule.name
  %td
    .d-flex
      %div
        = schedule.short_description.html_safe
      %div
        %span.round-icon{ 'data-toggle' => 'tooltip', 'data-title' => schedule.full_description, "data-html" => "true" }
          %i.fas.fa-info.icon-24
  %td
    .multi-ellipsis= schedule.message
  %td
    - if schedule.event_schedule?
      - schedule.channels.each do |ch|
        %span.ml-2.icon-24{'data-toggle' => 'tooltip', 'data-title' => t("shared.#{ch}")}
          = send("icon_#{ch}").html_safe
    - else
      %span.ml-2.icon-24{'data-toggle' => 'tooltip', 'data-title' => schedule.emails.join(', ')}
        = send("icon_email").html_safe

  %td= status_html(schedule.enabled?).html_safe
  %td= l(schedule.updated_at)
  %td.text-right
    = render 'action_buttons', schedule: schedule

app/views/schedules/_schedule_notify.haml
.form-group.schedule-notify
  %label= t('schedule.schedule_notify')
  .d-flex.align-items-center
    %label.mb-0.mr-2= t('schedule.every')
    - if f.object.event_schedule?
      = f.input :interval_value, label: false, input_html: {style: 'width: 100px;', class: 'input'}, wrapper_html: {class: 'mb-0 mr-2'}

    = f.input :interval_type, label: false, collection: Schedule.interval_types.keys.map { |k| [t("schedule.#{k}"), k] }, include_blank: false, input_html: {style: 'width: 100px;', class: 'input'}, wrapper_html: {class: 'mb-0 mr-2'}

    - if f.object.summary_schedule?
      .date-index{ 'data-week' => I18n.t('date.day_names').to_json }
        .d-flex.align-items-center
          %label.mb-0.mx-2= t('schedule.at_day')
          = f.input :date_index, as: :select, label: false, input_html: {style: 'width: 120px;', class: 'input', 'data-value' => f.object.date_index}, wrapper_html: {class: 'mb-0 mr-2'}

    %label.mb-0.mr-2= t('schedule.at')
    = f.input :follow_up_hour, label: false, collection: (0..23).to_a.map { |h| ["#{h}:00", h] }, include_blank: false, input_html: {style: 'width: 100px;', class: 'input'}, wrapper_html: {class: 'mb-0'}

    .ml-2
      %span.info.round-icon{ 'data-toggle' => 'tooltip', 'data-title' => '', 'data-info' => t("schedule.#{f.object.type.split('::').last.underscore}_full_info") }
        %i.fas.fa-info

app/views/schedules/edit.html.haml
- content_for :header_title do
  = "#{t('schedule.edit_schedule')}: #{@schedule.display_type}"

= render 'form'

app/views/schedules/index.html.haml
- content_for :header_title do
  = t('schedule.schedule')

.d-flex.justify-content-end.mb-3
  - if policy(Schedule).create?
    .btn-group
      %button.btn.btn-primary.btn-sm.shadow-sm.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button"}
        %i.fas.fa-plus
        = t('shared.add_new', name: t('schedule.schedule'))

      .dropdown-menu.dropdown-menu-right
        - schedule_types.each_with_index do |st, index|
          %a.dropdown-item{href: new_schedule_path(type: st[:type]), class: ('border-bottom' if index < schedule_types.length - 1)}
            %span.mr-2= st[:icon].html_safe
            = st[:label]

.card.shadow.mb-4
  .card-body
    = render partial: "shared/no_data", locals: { items: @schedules }

    - if @schedules.present?
      = render "shared/pagination_title", name: t('schedule.schedule')

      %table.table.table-hover.medium-width
        %thead
          %tr
            %th= t('shared.number')
            %th= t('schedule.name')
            %th= t('schedule.schedule')
            %th= t('schedule.message')
            %th= t('schedule.notify_to')
            %th= t('schedule.status')
            %th= t('shared.updated_at')
            %th

        %tbody
          = render partial: "schedule", collection: @schedules

    = render 'shared/pagination'

app/views/schedules/new.html.haml
- content_for :header_title do
  = "#{t('schedule.new_schedule')}: #{@schedule.display_type}"

= render 'form'